SELECT EMPLOYEE.Fname, EMPLOYEE.Lname, WORKS_ON.Hours
FROM EMPLOYEE 
INNER JOIN WORKS_ON ON EMPLOYEE.Ssn = WORKS_ON.Essn
INNER JOIN PROJECT ON WORKS_ON.Pno = PROJECT.Pnumber
INNER JOIN DEPARTMENT on EMPLOYEE.Dno = DEPARTMENT.Dnumber
WHERE DEPARTMENT.Dnumber = 5
AND PROJECT.Pname = 'ProductX'
AND WORKS_ON.Hours > 10;