SELECT EMPLOYEE.Fname, EMPLOYEE.Lname, DEPENDENT.Dependent_name, DEPENDENT.Relationship
FROM EMPLOYEE
INNER JOIN DEPENDENT ON EMPLOYEE.Ssn = DEPENDENT.Essn
WHERE EMPLOYEE.Fname = DEPENDENT.Dependent_name;